// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: evaluator.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dlvr {
  public static partial class Evaluator
  {
    static readonly string __ServiceName = "dlvr.Evaluator";

    static readonly grpc::Marshaller<global::Dlvr.EvaluateRequest> __Marshaller_dlvr_EvaluateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dlvr.EvaluateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dlvr.ProgressUpdate> __Marshaller_dlvr_ProgressUpdate = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dlvr.ProgressUpdate.Parser.ParseFrom);

    static readonly grpc::Method<global::Dlvr.EvaluateRequest, global::Dlvr.ProgressUpdate> __Method_Evaluate = new grpc::Method<global::Dlvr.EvaluateRequest, global::Dlvr.ProgressUpdate>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Evaluate",
        __Marshaller_dlvr_EvaluateRequest,
        __Marshaller_dlvr_ProgressUpdate);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dlvr.EvaluatorReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Evaluator</summary>
    public abstract partial class EvaluatorBase
    {
      public virtual global::System.Threading.Tasks.Task Evaluate(global::Dlvr.EvaluateRequest request, grpc::IServerStreamWriter<global::Dlvr.ProgressUpdate> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Evaluator</summary>
    public partial class EvaluatorClient : grpc::ClientBase<EvaluatorClient>
    {
      /// <summary>Creates a new client for Evaluator</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EvaluatorClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Evaluator that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EvaluatorClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EvaluatorClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EvaluatorClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Dlvr.ProgressUpdate> Evaluate(global::Dlvr.EvaluateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Evaluate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Dlvr.ProgressUpdate> Evaluate(global::Dlvr.EvaluateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Evaluate, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EvaluatorClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EvaluatorClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EvaluatorBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Evaluate, serviceImpl.Evaluate).Build();
    }

  }
}
#endregion
